### ISSUE TITLE
Warning: PDO::quote() 

### ISSUE THREAD

**Issue by m0rse** [DariusIII/newznab-tmux#35] opened 2015-01-07 10:44 UTC
getting Warning: PDO::quote() expects parameter 1 to be string, object given in **/lib/framework/db.php on line 374

*dev

when trying to download nzb

plus it just shows nzb in raw format:

Other > Misc FRNS15DDdiv0012BSF alt.binaries.cores alt.binaries.nl alt.binaries.x Part1of1.7CEE903BB9B042A5840924F6A3909F64@1420624712.local alt.binaries.cores alt.binaries.nl alt.binaries.x Part1of1.8E262F550D784F72AC291B2461967FAC@1420624712.local alt.binaries.cores alt.binaries.nl alt.binaries.x Part1of11.BD5372A86692497BA228404E3216A485@1420624712.local Part2of11.8E632A85D24445A9AFED565E5B0CD83D@1420624712.local Part3of11.955620406E784C08857D2704A9B7CC1A@1420624712.local Part4of11.06519030C6F640DE86D34E95C94AFE0B@1420624712.local Part5of11.E365BADCBB30473A97A7B4E64BDBA042@1420624712.local Part6of11.46E09AD47F8A4FBE8ABE06FCDAC21411@1420624712.local

**Comment by DariusIII** [comment] 2015-01-07 14:11
That error means that the escapestring is wrong, check apache/error logs for error, enable debugging in settings.php for more output.

**Comment by DariusIII** [comment] 2015-03-31 06:36
This should have been fixed. I will close the issue. If the problem is still present, feel free to reopen it.

**Closed by DariusIII** 2015-03-31 06:36 UTC
Labels: bug
