### ISSUE TITLE
SQL error for movies view via IMDB ID

### ISSUE THREAD

**Issue by RickDB** [DariusIII/newznab-tmux#99] opened 2015-10-04 21:14 UTC
Hi,

With nn+ you had the option to get an movie release overview by using its IMDB ID like this:

```
<site>/movies/?imdb=4685096
```

However with NN-TMUX this will result in an SQL error:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY m.imdbid ORDER BY MAX(r.postdate) desc LIMIT 20 OFFSET 0' at line 23
```

This was a handy feature as just like with TV shows you get all the releases for a particular movie grouped together and filter / sort afterwards.
Would be great if this could be fixed.

**Comment by DariusIII** [comment] 2015-10-05 06:37
Will fix ASAP.

**Comment by DariusIII** [comment] 2015-10-05 13:37
What version of mysql are you running? That query does not look like it should create a problem.

**Comment by RickDB** [comment] 2015-10-05 16:19
Latest Percona 5.5 build because 5.6 has random locking issues, not sure if 5.6 is stable enough today.

mysql -v output:

```
Server version: 5.5.37-35.0-657.trusty (Ubuntu)
```

**Comment by RickDB** [comment] 2015-10-05 17:50
Added debug out for the Movie.php query and tried manually in phpmyadmin to double check which reports the same error, this is the query it tries to run:

https://gist.github.com/RickDB/acf69c5928dcd5e769a3

**Comment by DariusIII** [comment] 2015-10-05 18:41
Update to latest dev, as some stuff is changed:
GROUP_CONCAT(r.failed ORDER BY r.postdate DESC SEPARATOR ',') AS grp_release_failed, line is no more. Have you run update_db.php after the pull?

**Comment by RickDB** [comment] 2015-10-05 18:54
Currently on master for stability as this is my main site now, is the dev branch safe to run at the moment?

Did run update_db.php as this was a new install so went with the docs from this repo which went pretty smoothly.

**Comment by RickDB** [comment] 2015-10-06 15:23
Updated to DEV branch but still getting the error sadly.

**Comment by DariusIII** [comment] 2015-10-06 15:50
Can you pastebin the whole error line?

**Comment by RickDB** [comment] 2015-10-06 16:02
That's the whole error line I get in the html page (<site>/movies/?imdb=4685096), checked php_errors.log from resouces/logs but nothing is logged there.

Managed to fix the errors and another one for NZBget and pushed the changes to this fork which is based on the latest DEV branch:

https://github.com/RickDB/newznab-tmux/commit/8d25c683d49cdc61346a2ee9d2cfd4d33e595458

Also contains a new git submodule for a theme, basically a darker themed Omicron but still needs some more work.

**Comment by RickDB** [comment] 2015-10-08 15:46
Were you able to reproduce the error and if so do you think the above fix is sufficient?

**Comment by DariusIII** [comment] 2015-10-08 15:54
No, no such error on my end.

**Comment by RickDB** [comment] 2015-10-08 16:27
That's odd, it's pretty much stock  from the DEV branch except for a few unrelated changes to template and RSS / nzbget so not sure why the resulting query would be different.
Tried with Omicron just in case it and got the same results, followed all the steps from movies.php up to the controller and see only those functions being called so not sure why it would get different results :(

When I add a print/echo $sql here:

https://github.com/RickDB/newznab-tmux/blob/c646f6944d09adb54d0fc3a66318795568429fcd/newznab/controllers/Movie.php#L276

It would display the following invalid query when I didn't remove the extra . AND from  getBrowseBy() (as it's in current DEV):

https://gist.github.com/RickDB/acf69c5928dcd5e769a3

Any way I can debug this further like with additional logging somewhere?

**Comment by DariusIII** [comment] 2016-02-16 21:52
Is this issue stil valid?

**Comment by DariusIII** [comment] 2016-02-25 08:25
I believe this issue is fixed. I am closing this, feel free to reopen it if the problem is still there.

**Closed by DariusIII** 2016-02-25 08:25 UTC
